Repository Soundbendor/smart-bin-app, pull requests merged in 2024-01, with the labels that each got.

#37 Create GitHub Issue and Pull Request templates
  .github/ISSUE_TEMPLATE/simple.yaml
  .github/ISSUE_TEMPLATE/user-story.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: refactor

#36 Add GitHub Pages worflow
  .github/workflows/github-pages.yaml
Labels: refactor

#53 Bluetooth | Establish genuine connection to device
  lib/main.dart
  lib/screens/bluetooth/bluetooth_page.dart
  lib/screens/connection/connect_page.dart
  lib/screens/splash/wifi_page.dart
  lib/widgets/wifi_configuration_widget.dart
Labels: enhancement

#59 Remove pubspec lock
  .gitignore
  pubspec.lock
Labels: refactor

#48 Rename issue templates
  .github/ISSUE_TEMPLATE/simple.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: refactor

#52 PubSub | Complete subscription functionality
  lib/pub_sub/subscriber.dart
Labels: enhancement

#47 Documentation | Create documentation for UI-related widgets
  lib/main.dart
  lib/screens/main/detection_page.dart
  lib/screens/main/detections_page.dart
  lib/screens/main/home_page.dart
  lib/screens/main/stats_page.dart
  lib/screens/splash/screen.dart
  lib/screens/splash/wifi_page.dart
  lib/widgets/detections.dart
  lib/widgets/heading.dart
  lib/widgets/wifi_configuration_widget.dart
Labels: documentation

#57 Code Comments | Wifi Config + Main + Heading widget
  lib/main.dart
  lib/widgets/heading.dart
  lib/widgets/wifi_configuration_widget.dart
  pubspec.yaml
Labels: documentation

#68 Documentation | Create documentation for annotation
  lib/main.dart
  lib/screens/main/annotation.dart
  lib/widgets/free_draw.dart
Labels: documentation

#69 UI | Implement simple database interactions
  lib/database/connection.dart
  lib/database/models/detection.dart
  lib/main.dart
  lib/pub_sub/subscriber.dart
  lib/screens/main/detection_page.dart
  lib/screens/main/detections_page.dart
  lib/widgets/detections.dart
  test/database/detections_queries_test.dart
  test/database/device_queries_test.dart
  test/shared.dart
  test/widgets/detection_list_test.dart
  test/widgets/detection_page_test.dart
Labels: enhancement

#71 Help Page | Implement Navigation Shell & Routing
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  lib/screens/main/help_page.dart
  lib/widgets/heading.dart
  lib/widgets/navigation_shell.dart
  lib/widgets/top_nav_bar.dart
  lib/widgets/wifi_configuration_widget.dart
Labels: enhancement, prio:medium

#72 Fix docs workflow
  .github/workflows/docs.yaml
Labels: documentation

#75 Database | Fetch Latest Detection
  lib/database/connection.dart
  lib/database/models/detection.dart
  lib/main.dart
  pubspec.yaml
  test/database/detections_queries_test.dart
Labels: enhancement
